console.log(`JavaScript loaded`)

const pattern1 = document.querySelector("#pattern-1")
const pattern2 = document.querySelector("#pattern-2")
const pattern3 = document.querySelector("#pattern-3")
const pattern4 = document.querySelector("#pattern-4")
const pattern5 = document.querySelector("#pattern-5")
const pattern6 = document.querySelector("#pattern-6")
const pattern7 = document.querySelector("#pattern-7")
const pattern8 = document.querySelector("#pattern-8")
const pattern9 = document.querySelector("#pattern-9")
const button1 = document.querySelector("#button-1")
const button2 = document.querySelector("#button-2")
const button3 = document.querySelector("#button-3")
const button4 = document.querySelector("#button-4")
const button5 = document.querySelector("#button-5")
const button6 = document.querySelector("#button-6")
const button7 = document.querySelector("#button-7")
const button8 = document.querySelector("#button-8")
const button9 = document.querySelector("#button-9")
const gameBoard = document.querySelector(".game-board")